name: New pipeline proposal
description: Propose a new pipeline for incorporation into nf-core
title: "New pipeline: <PROVISIONAL PIPELINE NAME>"
labels: new pipeline
type: pipeline
projects: pipeline
body:
  - type: checkboxes
    attributes:
      label: I confirm my proposal adheres to the nf-core pipeline requirements and recommendations
      description: You can see the requirements [here](https://nf-co.re/docs/guidelines/pipelines/overview).
      options:
        - label: I confirm
          required: true

  - type: input
    attributes:
      label: Pipeline title/name
      description: Names should be [lower case, without punctuation, and descriptive](https://nf-co.re/docs/guidelines/pipelines/requirements/workflow_name) (not 'fun' names).
      placeholder: rnaseq
    validations:
        required: true

  - type: input
    attributes:
      label: Keywords
      description: Provide a comma separated list of useful keywords for data type/analysis type/research field of the proposal (e.g. genomics, cancer, variant calling).
      placeholder: genomics, cancer, variant calling
    validations:
        required: true

  - type: textarea
    attributes:
      label: What is it about?
      description: Give a short summary of the purpose of the pipeline.
    validations:
        required: true

  - type: textarea
    attributes:
      label: Please provide a schematic diagram of the proposed pipeline
      description: Please use tool names as each 'node'. Drag and drop the image file into the text area.
    validations:
        required: true

  - type: textarea
    attributes:
      label: Why do we need a new pipeline?
      description: Describe the 'usefuless' or 'novelty' of the pipeline whether analytically or within nf-core.
    validations:
        required: true

  - type: textarea
    attributes:
      label: Who would be interested?
      description: Please give possible target audiences of the pipelines.
    validations:
        required: true

  - type: textarea
    attributes:
      label: What has been done so far
      description: Please describe the current status of the concept or code, or say if you have not stated.
    validations:
        required: true

  - type: input
    attributes:
      label: URL to existing work (if applicable)
      description: If you have already started working on the concept, please describe the current status 

  - type: input
    attributes:
      label: Are there any similar existing nf-core pipelines?
      description: Please give a comma separated list of similar or related existing [nf-core pipelines](https://nf-co.re/pipelines/).
