name: New RFC proposal
description: Propose a major new functionality for incorporation into nf-core
title: "New RFC: <short sentence describing proposal>"
labels: "new-rfc,proposed"
projects: nf-core/127
assignees:
  - nf-core/core
body:
  - type: input
    attributes:
      label: Summary
      description: Short 2-3 sentence summary of RFC proposal
    validations:
        required: true
  - type: input
    attributes:
      label: Champion
      description: "GitHub handle of the proposal's champion (if already found)"
      placeholder:
        e.g. Maxime Garcia (@maxulysse)
  - type: textarea
    attributes:
      label: Background & Motivation
      description: Provide the context of the proposal, summarising the existing status-quo or issues
      placeholder: 
    validations:
        required: true
  - type: textarea
    attributes:
      label: Goals
      description: Provide a 2-3 bullet point list of the main aims and objectives the outcome RFC aims to achieve 
      placeholder: |
        - Goal 1
        - Goal 2
        - Goal 3
    validations:
        required: true
  - type: textarea
    attributes:
      label: NonGoals
      description: Provide a 2-3 bullet point list of the main aims and objectives the outcome RFC aims NOT to achieve 
      placeholder: |
        - NonGoal 1
        - NonGoal 2
        - NonGoal 3
    validations:
        required: false
  - type: textarea
    attributes:
      label: Details
      description: Provide details of the proposed RFC, such as technical details of possible implementation
      placeholder: 
    validations:
        required: false
  - type: textarea
    attributes:
      label: References
      description: Post links to previous or current possibly-related discussions e.g. on slack
      placeholder: |
        - Slack discussion - <URL>
        - Original GitHub Issue - https://github.com/nf-core/<URL>
        - Prototype - https://github.com/nf-core/<URL>
    validations:
        required: false
