name: New pipeline proposal
description: Propose a new pipeline for incorporation into nf-core
title: "New pipeline: nf-core/<add provisional pipeline name here>"
labels: "new-pipeline,proposed"
projects: nf-core/104
body:
  - type: checkboxes
    attributes:
      label: "I confirm my proposed pipeline will follow nf-core guidelines. Most importantly, my pipeline:"
      description: You can see all the requirements [here](https://nf-co.re/docs/guidelines/pipelines/overview).
      options:
        - label: will be built with Nextflow and use the nf-core pipeline template.
          required: true
        - label: will pass nf-core lint tests and use standardized parameters.
          required: true
        - label: will be community-owned and developed within the nf-core organization.
          required: true
        - label: will be open source under the MIT license with proper credits and acknowledgments
          required: true
        - label: name will be descriptive, all lowercase, and without punctuation.
          required: true
        - label: will use the nf-core pipeline template and predominantly use official nf-core modules.
          required: true
        - label: will focus on a specific data/analysis type with appropriate scope.
          required: true
        - label: will have properly maintained documentation.
          required: true
        - label: will be must be bundled using versioned Docker/Singularity containers.
          required: true

  - type: input
    attributes:
      label: What is the last heading on the requirements page that is linked above? 
      description: Please copy and paste to confirm that you have visited the requirements pages. Because just ticking a box is easy.
    validations:
        required: true
        
  - type: input
    attributes:
      label: Pipeline title/name
      description: Names should be [lower case, without punctuation, and descriptive](https://nf-co.re/docs/guidelines/pipelines/requirements/workflow_name) (not 'fun' names).
      placeholder: rnaseq
    validations:
        required: true

  - type: input
    attributes:
      label: Keywords
      description: Provide a comma separated list of useful keywords for data type/analysis type/research field of the proposal (e.g. genomics, cancer, variant calling).
      placeholder: genomics, cancer, variant calling
    validations:
        required: true

  - type: textarea
    attributes:
      label: What is it about?
      description: Give a short summary of the purpose of the pipeline.
      placeholder: An RNA sequencing analysis pipeline using STAR, RSEM, HISAT2 or Salmon with gene/isoform counts and extensive quality control. 
    validations:
        required: true

  - type: textarea
    attributes:
      label: Please provide a schematic diagram of the proposed pipeline
      description: Please use tool names as each 'node'. Drag and drop the image file into the text area to upload.
      placeholder: ![](https://your.url/image/png)
    validations:
        required: true

  - type: textarea
    attributes:
      label: Why do we need a new pipeline?
      description: Describe the 'usefuless' or 'novelty' of the pipeline whether analytically or within nf-core.
    validations:
        required: true

  - type: textarea
    attributes:
      label: Who would be interested?
      description: Please give possible target audiences of the pipelines.
      placeholder: Researchers working on transcriptomics.
    validations:
        required: true

  - type: textarea
    attributes:
      label: What has been done so far
      description: Please describe the current status of the concept or code, or say if you have not stated.
      placeholder: I have started making nf-core modules for tools I would use in the proposed pipeline.
    validations:
        required: true

  - type: input
    attributes:
      label: URL to existing work (if applicable)
      description: If you have already started working on the concept, please describe the current status
      placeholder: https://github.com/nf-core/rnaseq

  - type: input
    attributes:
      label: Are there any similar existing nf-core pipelines?
      description: Please give a comma separated list of similar or related existing [nf-core pipelines](https://nf-co.re/pipelines/).
      placeholder: sarek, oncoanalyzer, rnavar
